version: "3.9"
services:
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
      - "4466:4466"
    networks:
      - web-net
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            user: root
            password: password
            rawAccess: true
            port: 3306
            migrations: true

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: posts
    networks:
      - web-net
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql/data
  
  restapi:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-mysql-api
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - web-net
    restart: always

networks:
  web-net:
    external: true
     
volumes:
  mysql-data:
